# Generated by https://quicktype.io
from dataclasses import dataclass


@dataclass
class CancelAllOrdersResponse:
    code: int
    msg: str


@dataclass
class ListenKeyResponse:
    listenKey: str


@dataclass
class MarkPriceResponse:
    symbol: str
    markPrice: str
    indexPrice: str
    estimatedSettlePrice: str
    lastFundingRate: str
    nextFundingTime: float
    interestRate: str
    time: float


@dataclass
class PositionInformationResponse:
    symbol: str
    positionAmt: str
    entryPrice: str
    breakEvenPrice: str
    markPrice: str
    unRealizedProfit: str
    liquidationPrice: str
    leverage: str
    maxNotionalValue: str
    marginType: str
    isolatedMargin: str
    isAutoAddMargin: str
    positionSide: str
    notional: str
    isolatedWallet: str
    updateTime: float
