# Generated by https://quicktype.io
from dataclasses import dataclass

@dataclass(kw_only=True)
class CancelAllOrdersResponse:
    code: int
    msg: str


@dataclass(kw_only=True)
class ListenKeyResponse:
    listenKey: str
